# Site/SEO settings
email: tyler.devtcn@gmail.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Tyler Duckworth
title: Tyler Duckworth
description: >
  This site details my creative work, projects, and general thoughts. 
url: http://tyler-duckworth.github.io
twitter_username: t_duck15
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/t_duck15
  # - name: instagram
  #   url: https://www.instagram.com/thomas.vaeth/
  # - name: linkedin
  #   url: https://www.linkedin.com/in/thomasvaeth/
  - name: github
    url: https://github.com/tyler-duckworth
  # - name: codepen
  #   url: https://codepen.io/thomasvaeth/

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Tyler Duckworth
    bio: Tyler Duckworth was born in Knoxville, TN and currently attends the L&N STEM Academy. He has interests in things varying from digital design to programming. He works with the L&N STEMpunks Robotics team to model and program robots. 
    url: http://tyler-duckworth.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
